name: Tests

on: [push]

jobs:
  build:

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-16.04, ubuntu-18.04]
        swift: ["5.0", "5.1"]
        include:
          - os: macos-latest
            swift: "local"

    steps:
    - uses: actions/checkout@v1
    - name: Run tests in local
      if: contains(matrix.os, 'macOS')
      run: swift test -v
    - name: Run tests in xenial container
      if: matrix.os == 'ubuntu-16.04'
      run: docker run -v ${{ github.workspace }}:/mnt -w /mnt --cap-add sys_ptrace -i --rm swift:${{ matrix.swift }}-xenial swift test -v
    - name: Run tests in bionic container
      if: matrix.os == 'ubuntu-18.04'
      run: docker run -v ${{ github.workspace }}:/mnt -w /mnt --cap-add sys_ptrace -i --rm swift:${{ matrix.swift }}-bionic swift test -v
