name: Tests

on: [push]

jobs:
  test_linux:
    runs-on: "ubuntu-18.04"
    strategy:
      matrix:
        os: ["xenial", "bionic"]
        swift: ["5.1.0", "5.1"]
    steps:
      - uses: actions/checkout@v1
      - name: Run tests
        run: docker run -v ${{ github.workspace }}:/mnt -w /mnt --cap-add sys_ptrace -i --rm swift:${{ matrix.swift }}-${{ matrix.os }} swift test -v

  test_macos:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macOS-latest]
        xcode-version: ["11.3"]

    steps:
      - uses: actions/checkout@v1
      - uses: sinoru/actions-setup-xcode@v1.1
        with:
          xcode-version: ${{ matrix.xcode-version }}
      - name: Run tests
        run: swift test -v
