name: Tests

on: [push]

jobs:
  build:

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-16.04, ubuntu-18.04, macOS-latest]
        swift: [5.0, 5.1]
        exclude:
          - os: macos-latest
            swift: 5.0

    steps:
    - uses: actions/checkout@v1
    - name: Run tests
      if: contains(runner.os, 'macOS')
      run: swift test -v
    - name: Run tests
      if: contains(runner.os, 'ubuntu-16.04')
      uses: docker://swift:${{ matrix.swift }}-xenial
      with:
        args: swift test -v
    - name: Run tests
      if: contains(runner.os, 'ubuntu-18.04')
      uses: docker://swift:${{ matrix.swift }}-bionic
      with:
        args: swift test -v
